name: german-credit-train
channels:
  - conda-forge
  - defaults

dependencies:
- python=3.6.2
- pip
- pip:
  # Azure ML
  - azureml-sdk[explain]==1.0.83
  - azureml-dataprep[fuse,pandas]
  - azureml-contrib-pipeline-steps==1.0.83
#  - azureml-contrib-explain-model==1.0.83
  - azureml-contrib-interpret==1.0.83
#  - inference-schema[numpy-support]==1.0.83
  # Other
  - scipy==1.2.1
  - scikit-learn==0.20.3  
  - joblib==0.13.2
  - pandas==0.25.3
  - numpy==1.16.2
  - python-dotenv==0.10.3
  - tqdm==4.36.1