computeType: AKS

autoScaler:
    autoscaleEnabled: True
    minReplicas: 1
    maxReplicas: 3
    refreshPeriodInSeconds: 10
    targetUtilization: 70

containerResourceRequirements:
  cpu: 1
  memoryInGB: 0.5

authEnabled: True
tokenAuthEnabled: True
appInsightsEnabled: True
sslEnabled: False
