name: german-credit-score

channels:
  - conda-forge
  - defaults

dependencies:
- python=3.6.2
- pip
- pip:
  # Azure ML (azureml-defaults is required for inference)
  - azureml-defaults>=1.0.45
  - inference-schema[numpy-support]
  # Other
  - scipy==1.2.1
  - scikit-learn==0.20.3  
  - joblib==0.13.2
  - pandas==0.25.3
  - numpy==1.16.2