name: german-credit-train
channels:
  - conda-forge
  - defaults
dependencies:
- python=3.6.2
- pip
- pip:
  # Azure ML
  - azureml-defaults>=1.8.0
  - azureml-dataprep[pandas]
  - azureml-sdk[explain,interpret]
  - azureml-contrib-interpret
  # Other
  - scikit-learn==0.20.3
  - joblib==0.13.2
  - pandas==0.25.3