  
variables: 
 - template: german-credit-config.yml

trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: AzureCLI@2
    displayName: 'Install AML CLI'
    inputs:
      azureSubscription: $(ml-workspace-connection)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az extension add -n azure-cli-ml

  - task: AzureCLI@2
    displayName: 'Attach to workspace'
    inputs:
      azureSubscription: $(ml-workspace-connection)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az ml folder attach -g $(ml-workspace-rg) -w $(ml-workspace-name)

  - task: AzureCLI@2
    displayName: 'Deploy model to ACI for QA'
    inputs:
      azureSubscription: $(ml-workspace-connection)
      workingDirectory: $(ml-model-path)
      scriptLocation: inlineScript
      scriptType: bash
      inlineScript: |
        LATEST_VERSION=`az ml model list -n $(ml-model-name) --query '[0].version'`
        az ml model deploy -n german-credit-aci-qa \
          --model $(ml-model-name):$LATEST_VERSION \
          --inference-config-file config/inference-config.yml \
          --deploy-config-file config/deployment-config-aci-qa.yml \
          --overwrite

  - task: AzureCLI@2
    displayName: 'Deploy model to AKS for Production'
    inputs:
      azureSubscription: $(ml-workspace-connection)
      workingDirectory: $(ml-model-path)
      scriptLocation: inlineScript
      scriptType: bash
      inlineScript: |
        LATEST_VERSION=`az ml model list -n $(ml-model-name) --query '[0].version'`
        az ml model deploy -n german-credit-aks-prod \
          --compute-target $(ml-aks-cluster) \
          --model $(ml-model-name):$LATEST_VERSION \
          --inference-config-file config/inference-config.yml \
          --deploy-config-file config/deployment-config-aks-prod.yml \
          --overwrite
