trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


variables: { 
  ml-workspace-connection: 'aml-workspace-connection' ,
}

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: $(ml-workspace-connection)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az extension add -n azure-cli-ml'
