variables:
  ml-workspace-connection: 'aml-workspace-connection'
  ml-workspace-name: 'csamlfsi-ws'
  ml-workspace-rg: 'csamlfsi-rg'
  ml-compute-name: 'amlcluster'
  ml-experiment-name: 'german-credit-automl-ci'
  ml-dataset-name: 'german_credit_dataset'
  ml-model-path: 'models/german-credit-automl'
  ml-script-arguments: --DATASET_NAME $(ml-dataset-name)

trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: AzureCLI@2
    displayName: 'Install AML CLI'
    inputs:
      azureSubscription: $(ml-workspace-connection)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az extension add -n azure-cli-ml

  - task: AzureCLI@2
    displayName: 'Train model (AutoML)'
    inputs:
      azureSubscription: $(ml-workspace-connection)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      workingDirectory: $(ml-model-path)
      inlineScript: |
        az ml run submit-script \
        --resource-group $(ml-workspace-rg) \
        --workspace-name $(ml-workspace-name) \
        --conda-dependencies train-config/conda_train.yml \
        --ct $(ml-compute-name) \
        --experiment-name $(ml-experiment-name) \
        --output-metadata-file $(Build.ArtifactStagingDirectory)/run.json \
        train.py \
        $(ml-script-arguments)

  # - task: CopyFiles@2
  #   displayName: 'Copy deployment configs'
  #   inputs:
  #     SourceFolder: '$(ml-model-path)/inference-config'
  #     Contents: '*'
  #     TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: CopyFiles@2
    displayName: 'Copy Python code'
    inputs:
      SourceFolder: '$(ml-model-path)'
      Contents: '**/*.py'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish run and details'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'model-artifacts'
      publishLocation: 'Container'