name: german-credit-train
channels:
  - conda-forge
  - defaults
dependencies:
- python=3.6.2
- pip
- pip:
  - azureml-sdk[explain,automl]
  - azureml-widgets
  - azureml-contrib-explain-model
  - azureml-contrib-interpret
